#!/bin/bash
clear

 read -r -p 'Pleas enter user name: ' user

 if  grep -q  $user /etc/passwd  ||  grep -q  $user /etc/group ;then
        echo ERROR -- User $user OR group $user already exist

 else
         password=${user}123
         sudo adduser $user --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
         echo "User $user added successfully!"
         echo "$user:$password" | sudo chpasswd
         echo "Password for user $user changed successfully"
 fi
 echo " "
