#!/bin/bash

 clear
 echo "===All Users===="
 ls /home/
 echo "================"
 echo
 read -r -p 'Pleas enter the user you want to delete from the list above: ' user

 sudo deluser --remove-home $user

